check connect

diff --git a/.github/workflows/beckend-dev-cicd.yml b/.github/workflows/beckend-dev-cicd.yml
--- a/.github/workflows/beckend-dev-cicd.yml
+++ b/.github/workflows/beckend-dev-cicd.yml
@@ -32,7 +32,7 @@ jobs:
 
     steps:
       - name: Check SSH connectivity
-        run: nc -vz 34.55.22.196 22 || echo "SSH connection failed"
+        run: nc -vz ${{ secrets.SERVER_HOST }} 22 || echo "SSH connection failed"
 
       - name: Deploy to VPS
         uses: appleboy/ssh-action@v0.1.6
